//package rconnect.retvens.technologies.Authentication
//
//<?xml version="1.0" encoding="utf-8"?>
//<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
//xmlns:app="http://schemas.android.com/apk/res-auto"
//xmlns:tools="http://schemas.android.com/tools"
//android:layout_width="match_parent"
//android:layout_height="match_parent"
//tools:context=".Authentication.LoginScreen">
//
//
//
//<androidx.constraintlayout.widget.ConstraintLayout
//android:id="@+id/frame1"
//android:layout_width="wrap_content"
//android:layout_height="match_parent"
//app:layout_constraintTop_toTopOf="parent"
//app:layout_constraintEnd_toStartOf="@+id/frame2"
//app:layout_constraintBottom_toBottomOf="parent"
//app:layout_constraintStart_toStartOf="parent"
//android:background="@color/secondarybackground"
//>
//
//
//
//<TextView
//android:layout_width="370dp"
//android:layout_height="wrap_content"
//android:layout_marginTop="120dp"
//android:fontFamily="@font/inter_bold"
//android:text="Manage your properties and guest in easy way"
//android:textColor="@color/black"
//android:textFontWeight="700"
//android:textAlignment="center"
//android:textSize="@dimen/boldHeading"
//app:layout_constraintEnd_toEndOf="parent"
//app:layout_constraintStart_toStartOf="parent"
//app:layout_constraintTop_toTopOf="parent"
//
///>
//
//<ImageView
//android:layout_width="wrap_content"
//android:layout_height="500dp"
//android:src="@drawable/vector_firstonboarding"
//app:layout_constraintBottom_toBottomOf="parent"
//app:layout_constraintEnd_toEndOf="parent"
//app:layout_constraintHorizontal_bias="0.0"
//app:layout_constraintStart_toStartOf="parent"
//app:layout_constraintTop_toTopOf="parent"
//app:layout_constraintVertical_bias="0.823" />
//
//</androidx.constraintlayout.widget.ConstraintLayout>
//
//<androidx.core.widget.NestedScrollView
//android:id="@+id/frame2"
//android:layout_width="700dp"
//android:layout_height="match_parent"
//android:background="@color/primarybackground"
//app:layout_constraintEnd_toEndOf="parent"
//app:layout_constraintHorizontal_bias="0.987"
//app:layout_constraintTop_toTopOf="parent"
//>
//
//
//
//
//</androidx.core.widget.NestedScrollView>
//
//</androidx.constraintlayout.widget.ConstraintLayout>